{
 "title": "Item service monitoring",
 "description": "All metrics of Item service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request percentile",
   "type": "timeseries",
   "description": "P75, P90, P95 and P99 for each API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ecom_api_request_duration_ms_bucket{job=\"svc_item\"}[5m]))",
     "legendFormat": "{{svc}}-P95-{{path}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "description": "Total request errors by type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(ecom_api_error_count{job=\"svc_item\"}[5m])",
     "legendFormat": "{{svc}}-{{path}}-{{type}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Request rate per API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ecom_api_request_count{job=\"svc_item\"}[5m])",
     "legendFormat": "{{svc}}-{{method}}-{{path}}-{{status}}"
    }
   ]
  }
 ]
}