{
 "title": "Mornitoring system ecomere",
 "time": { "from": "2023-02-04T11:01:40.600Z", "to": "2023-02-04T11:14:06.000Z" },
 "panels": [
  {
   "title": "API layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API throughput (per sec)",
   "type": "timeseries",
   "description": "The API throughput should follow the design here\n\nhttps://xsdd-docs-payment.intra.rakuten-it.com/projects/one-operation/Specifications/system-design#non-functional-requirements\n\nAvg: 50QPS\nPeak: 200QPS\n\nIt is abnormal if the QPS is too high.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ecom_api_request_count[$__rate_interval])",
     "legendFormat": "{{env}}-{{method}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "Percentile API response time (ms)",
   "type": "timeseries",
   "description": "The response time should follow the design here https://xsdd-docs-payment.intra.rakuten-it.com/projects/one-operation/Specifications/system-design#non-functional-requirements\n\nP75 = 100ms\nP95 = 200ms\nP99 = 300ms\nP100 = 500ms\n\nIt is abnormal if the response time is too high.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(ecom_api_request_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{method}}-{{path}}-p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(ecom_api_request_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{method}}-{{path}}-p90"
    },
    {
     "expr": "histogram_quantile(0.75, rate(ecom_api_request_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{method}}-{{path}}-p75"
    },
    {
     "expr": "histogram_quantile(0.50, rate(ecom_api_request_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{method}}-{{path}}-p50"
    }
   ]
  },
  {
   "title": "Avg API response time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ecom_api_request_duration_ms_sum[$__rate_interval]) / rate(ecom_api_request_duration_ms_count[$__rate_interval])",
     "legendFormat": "{{env}}-{{method}}-{{path}}"
    }
   ]
  },
  {
   "title": "Num API errors details",
   "type": "graph",
   "description": "Since the queries are internal, so it is abnormal if we got API errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_api_request_count{status!=\"200\"}[$__rate_interval])",
     "legendFormat": "{{env}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "Num API non-2xx responses",
   "type": "graph",
   "description": "It is abnormal if we have many errors here, since all data is supposed to be existing in DB already, and all the requests are internal.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_api_request_count{status!=\"200\"}[$__rate_interval])",
     "legendFormat": "{{env}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "API 404 responses (per 10sec)",
   "type": "graph",
   "description": "The data is supposed to be existing in DB, and the query from internal system, so it is abnormal if the data not found in DB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ecom_api_request_count{status=\"404\"}[$__rate_interval]) * 10",
     "legendFormat": "{{env}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "API 500 responses (per 10sec)",
   "type": "graph",
   "description": "The data is supposed to be existing in DB, and the query from internal system, so it is abnormal if the data not found in DB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ecom_api_request_count{status=\"500\"}[5m]) * 10",
     "legendFormat": "{{env}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "DB layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Num DB query errors",
   "type": "graph",
   "description": "It is abnormal on DB layer if we got many errors here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_db_error_count[$__rate_interval])",
     "legendFormat": "{{env}}-{{db}}-{{target}}-{{type}}"
    }
   ]
  },
  {
   "title": "Num DB query no data",
   "type": "graph",
   "description": "Since the data is supposed to be existing on DB already, so its abnormal if we got errors here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_db_error_count{type=\"no_row\"}[$__rate_interval])",
     "legendFormat": "{{env}}-{{db}}-{{target}}"
    }
   ]
  },
  {
   "title": "Num rows returned",
   "type": "graph",
   "description": "Num rows returned by a query. \n\nSince we may have many records for the same barcode value, so if we have many records (eg: hundreds) returned, so it may slow down the response time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ecom_db_num_rows_returned", "legendFormat": "{{env}}-{{db}}-{{target}}" }
   ]
  },
  {
   "title": "Num DB query error internal",
   "type": "graph",
   "description": "Since the data is supposed to be existing on DB already, so its abnormal if we got errors here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_db_error_count{type=\"internal\"}[$__rate_interval])",
     "legendFormat": "{{env}}-{{db}}-{{target}}-{{type}}"
    }
   ]
  },
  {
   "title": "Query duration (ms)",
   "type": "timeseries",
   "description": "Query duration in ms\n\nSince all queries are indexes and the returned rows are supposed to be not much, so its abnormal on DB layer if we get high duration here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(ecom_db_query_dur_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{db}}-{{target}}-p50"
    }
   ]
  },
  { "title": "HTTP Clients (Extenal service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Num requests errors",
   "type": "timeseries",
   "description": "How many errors occurred by error type when request to external services\n\nIt is abnormal on the External services layer if we got many errors here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ecom_http_client_err_count[$__rate_interval])",
     "legendFormat": "{{env}}-{{service}}-{{path}}-{{type}}"
    }
   ]
  },
  {
   "title": "Num requests no data",
   "type": "graph",
   "description": "Since the data is supposed to be existing on the External services side already, so its abnormal if we got many 404 responses here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_http_client_response_code_count{code!=\"200\"}[$__rate_interval])",
     "legendFormat": "{{env}}-{{service}}-{{path}}"
    }
   ]
  },
  {
   "title": "Num requests per status code",
   "type": "graph",
   "description": "Since the data is supposed to be existing on the External services side already, so its abnormal if we got non-2xx status here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ecom_http_client_response_code_count[$__rate_interval])",
     "legendFormat": "{{env}}-{{service}}-{{path}}-{{code}}"
    }
   ]
  },
  {
   "title": "Requests duration (ms)",
   "type": "graph",
   "description": "Query to the External services duration in ms\n\nSince all queries are indexes and the returned rows are supposed to be not much, so its abnormal on the External services layer if we get high duration here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(ecom_http_client_response_dur_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{service}}-{{path}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ecom_http_client_response_dur_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{service}}-{{path}}-p95"
    },
    {
     "expr": "histogram_quantile(0.75, rate(ecom_http_client_response_dur_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{service}}-{{path}}-p75"
    },
    {
     "expr": "histogram_quantile(0.50, rate(ecom_http_client_response_dur_ms_bucket[$__rate_interval]))",
     "legendFormat": "{{env}}-{{service}}-{{path}}-p50"
    }
   ]
  }
 ]
}